# Generated by Django 3.0.3 on 2020-02-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('term_length', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
