# Generated by Django 3.0.3 on 2020-02-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='term_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(choices=[('PC', 'Power of Credit'), ('NF', 'New Fixed')], max_length=2),
        ),
    ]
