# Generated by Django 3.0.3 on 2020-02-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0002_auto_20200205_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(choices=[('Power of Credit', 'Power of Credit'), ('New Fixed', 'New Fixed')], max_length=15),
        ),
    ]
